name: parallel
on: workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
  checkout:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: List content
        run: pwd;ls -al
      - name: Run Maven clean
        run: mvn clean
  run_unit_tests:
    needs: [setup, checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: pwd;mvn clean test
  run_integration_tests:
    needs: [setup, checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Run integration tests
        run: pwd;mvn clean verify
  summary:
    needs: [ setup, checkout, run_unit_tests, run_integration_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Print summary
        run: echo "This is the summary"
